import { CompanyProfile } from './state';

export type CertificatePayload = {
  companyNumber: string;
  certificateId: string;
  incorporatedAt: string;
};

function uid() {
  return Math.random().toString(16).slice(2) + Date.now().toString(16);
}

export function generateCompanyNumber(): string {
  // UK company number is typically 8 chars; simulate numeric.
  const n = Math.floor(10_000_000 + Math.random() * 89_999_999);
  return String(n);
}

export function generateCertificate(profile: CompanyProfile, companyNumber: string): CertificatePayload {
  return {
    companyNumber,
    certificateId: `CERT-${uid().toUpperCase()}`,
    incorporatedAt: new Date().toISOString(),
  };
}

export function downloadCertificateTxt(profile: CompanyProfile, payload: CertificatePayload) {
  const lines = [
    'CERTIFICATE OF INCORPORATION (SIMULATION)',
    '----------------------------------------',
    `Company name: ${profile.companyName}`,
    `Company number: ${payload.companyNumber}`,
    `Company type: Private Limited Company (Ltd)`,
    `Registered office: ${profile.registeredOfficeAddress}`,
    `SIC code: ${profile.sicCode}`,
    `Incorporated at: ${new Date(payload.incorporatedAt).toUTCString()}`,
    '',
    'This document is generated by the prototype for demonstration only.',
  ];

  const blob = new Blob([lines.join('\n')], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = 'certificate-of-incorporation.txt';
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}
